import type { FeatureFlags } from "./features";

export type HomeShortcut = {
  key: string;
  flagKey?: keyof FeatureFlags;
  title: string;
  subtitle: string;
  icon: "briefcase" | "calendar" | "file-text" | "globe" | "clock" | "help-circle" | "check-circle" | "message-square" | "bell" | "bookmark" | "heart" | "home" | "file" | "clipboard" | "alert-triangle" | "map" | "map-pin" | "message-circle" | "settings";
  route: string;
};

export const homeShortcuts: HomeShortcut[] = [
  {
    key: "learning",
    flagKey: "learning",
    title: "Learn",
    subtitle: "Deutsch",
    icon: "bookmark",
    route: "/(tabs)/learn",
  },
  {
    key: "community",
    flagKey: "community",
    title: "Community",
    subtitle: "Connect",
    icon: "message-square",
    route: "/(tabs)/community",
  },
  {
    key: "jobs",
    flagKey: "jobs",
    title: "Jobs",
    subtitle: "Browse",
    icon: "briefcase",
    route: "/(tabs)/jobs",
  },
  {
    key: "events",
    flagKey: "events",
    title: "Events",
    subtitle: "Nearby",
    icon: "calendar",
    route: "/events",
  },
  {
    key: "documents",
    flagKey: "documents",
    title: "Documents",
    subtitle: "Guides",
    icon: "file-text",
    route: "/documents",
  },
  {
    key: "countries",
    flagKey: "countries",
    title: "Countries",
    subtitle: "Starter packs",
    icon: "globe",
    route: "/countries",
  },
  {
    key: "timeline",
    flagKey: "timeline",
    title: "Timeline",
    subtitle: "90 days",
    icon: "clock",
    route: "/timeline",
  },
  {
    key: "services",
    flagKey: "services",
    title: "Services",
    subtitle: "Trusted",
    icon: "help-circle",
    route: "/services",
  },
  {
    key: "checklist",
    flagKey: "checklist",
    title: "Checklist",
    subtitle: "Progress",
    icon: "check-circle",
    route: "/checklist",
  },
  {
    key: "deadlines",
    flagKey: "deadlines",
    title: "Deadlines",
    subtitle: "Due dates",
    icon: "calendar",
    route: "/deadlines",
  },
  {
    key: "documents-tracker",
    flagKey: "documents",
    title: "Doc Tracker",
    subtitle: "Expiry",
    icon: "file-text",
    route: "/documents-tracker",
  },
  {
    key: "phrasebook",
    flagKey: "phrasebook",
    title: "Phrasebook",
    subtitle: "Phrases",
    icon: "message-square",
    route: "/phrasebook",
  },
  {
    key: "residency-reminders",
    flagKey: "reminders",
    title: "Reminders",
    subtitle: "Residency",
    icon: "bell",
    route: "/residency-reminders",
  },
  {
    key: "school",
    flagKey: "school",
    title: "School",
    subtitle: "Enrollment",
    icon: "bookmark",
    route: "/school",
  },
  {
    key: "support",
    flagKey: "support",
    title: "Support",
    subtitle: "Wellbeing",
    icon: "heart",
    route: "/support",
  },
  {
    key: "housing",
    flagKey: "housing",
    title: "Housing",
    subtitle: "Safety",
    icon: "home",
    route: "/housing-safety",
  },
  {
    key: "tax",
    flagKey: "tax",
    title: "Tax Basics",
    subtitle: "Deadlines",
    icon: "file",
    route: "/tax",
  },
  {
    key: "forms",
    flagKey: "forms",
    title: "Forms",
    subtitle: "Guided",
    icon: "clipboard",
    route: "/forms",
  },
  {
    key: "emergency",
    flagKey: "emergency",
    title: "Emergency",
    subtitle: "Numbers",
    icon: "alert-triangle",
    route: "/emergency",
  },
  {
    key: "guides",
    flagKey: "guides",
    title: "Guides",
    subtitle: "Essentials",
    icon: "map",
    route: "/guides",
  },
  {
    key: "locations",
    flagKey: "locations",
    title: "Locations",
    subtitle: "Nearby",
    icon: "map-pin",
    route: "/locations",
  },
  {
    key: "chat",
    flagKey: "chat",
    title: "Chat",
    subtitle: "Community",
    icon: "message-circle",
    route: "/chat",
  },
  {
    key: "settings",
    title: "Settings",
    subtitle: "Preferences",
    icon: "settings",
    route: "/settings",
  },
];
